apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fileshare-pvc
  namespace: fileshare
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
  storageClassName: azurefile-csi