# apiVersion: argoproj.io/v1alpha1
# kind: Application
# metadata:
#   name: kube-prometheus-stack
#   namespace: argocd
#   finalizers:
#     - resources-finalizer.argocd.argoproj.io
# spec:
#   project: azure-demo
#   sources:
#     # 1) Chart 来源（Prometheus Community 仓库）
#     - repoURL: https://prometheus-community.github.io/helm-charts
#       chart: kube-prometheus-stack
#       targetRevision: 76.4.0 # 你可以替换成对应版本号
#       helm:
#         releaseName: my-kube-prometheus-stack
#         valueFiles:
#           # 引用另一个 source（ref: values）里的文件
#           - $values/monitoring/values_openebs-hostpath.yaml

#     # 2) Git 仓库（存放 values-openebs-haproxy.yaml）
#     - repoURL: https://gitlab.local.seems.fit/root/devops.git
#       targetRevision: HEAD
#       ref: values

#   destination:
#     server: https://kubernetes.default.svc
#     namespace: monitoring
#   syncPolicy:
#     automated:
#       selfHeal: true
#       prune: true
#     syncOptions:
#       - CreateNamespace=true
#       - ServerSideApply=true
