apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: azure-test
  sources:
    - repoURL: https://traefik.github.io/charts
      chart: traefik
      targetRevision: 37.0.0
      helm:
        releaseName: traefik
        valueFiles:          
          - $values/traefik/values.yaml     
    - repoURL: https://github.com/eatmybigJB/azure_devops.git
      targetRevision: HEAD
      ref: values

  destination:
    server: https://kubernetes.default.svc
    namespace: traefik
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true

