# ---
# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: argocd-server-og
#   namespace: argocd
#   annotations:
#     cert-manager.io/cluster-issuer: org-issuer
# spec:
#   rules:
#   - host: argocd.192.168.1.90.nip.io
#     http:
#       paths:
#       - path: /
#         pathType: ImplementationSpecific
#         backend:
#           service:
#             name: argocd-server
#             port:
#               name: https
#   tls:
#   - hosts:
#     - argocd.192.168.1.90.nip.io
#     secretName: argocd-cert-og
